version: "3"
services:
  mysql:
    image: mysql:5.6.27
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: david
      MYSQL_PASSWORD: abcd1234
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  mysqldata:
    driver: local
